.TH fsstat 1 ${VERSION}

.SH NAME

.PP
fsstat - it stats file system entries

.SH SYNOPSIS

.PP
fsstat [\fIOPTION\fR | \fIPATH\fR]...

.SH DESCRIPTION

.PP
It stats different types of info about file system entries given their
\fIPATH\fR(s) and \fIOPTION\fR(s) used before them.

.SH INFO TYPE OPTIONS

.PP
These options specify the info type to be stat. At least one must always be
specified:

.TP
.B -t
it stats its type: which can be regular (r), directory (d), symlink (l),
character (c), block (b), socket (s) or fifo (f).

.TP
.B -s
it stats its byte size.

.TP
.B -hs
it stats its size in the most formidable human-size unit: which can be:
gigabyte (GB), megabyte (MB), kilobyte (kB) or byte (B).

.TP
.B -p
it stats its read (r), write (w), execute (x) and lack (-) permissions for user,
group and others, respectively.

.TP
.B -op
it stats its permissions in octal base.

.TP
.B -u
it stats the user that owns it.

.TP
.B -ui
it stats the UID of the user that owns it.

.TP
.B -g
it stats the group that owns it.

.TP
.B -gi
it stats the GID of the group that owns it.

.TP
.B -md
it stats its last modified date.

.SH SYMLINK OPTIONS

.PP
These options specify how symlinks are handled. By default, it does not follows
them:

.TP
.B -fl
it follows symlinks.

.TP
.B -ul
it unfollows symlinks.

.SH EXAMPLES

.nf
$ fsstat -p entry0 entry1 -hs entry2;
$ fsstat -t symlink0 -ul symlink1;
.fi

.SH EXIT CODES

.PP
It returns 0 on success, and 1 on failure.

.SH SOURCE CODE

.PP
Its source code is available at <https://github.com/skippyr/fsstat>.

.SH HELP

.PP
If you need help about this project, open a new issue in its issues page
(<https://github.com/skippyr/fsstat/issues>) or send me an e-mail
(<mailto:skippyr.developer@gmail.com>) describing what is going on.

.SH CONTRIBUTING

.PP
This project is open to review and possibly accept contributions, specially
fixes and suggestions. If you are interested, send your contribution to its
pull requests page (<https://github.com/skippyr/fsstat/pulls>) or to my
e-mail (<mailto:skippyr.developer@gmail.com>).

.PP
By contributing to this project, you must agree to license your work under the
same license that the project uses.

.SH LICENSE

.PP
This project is licensed under the BSD-3-Clause License. Refer to the LICENSE
file that comes in its source code for license and copyright details.
